relativeURLs = true
title = "Gautam Rao"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]
exclude: ["README.md"]

[params]
    shortbio = "Associate Professor of Economics, Harvard University"
    logo = "gr.jpg" 
    
